/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 postit.gltf --transform
Files: postit.gltf [13.17KB] > postit-transformed.glb [3.64KB] (72%)
Author: IronEqual (https://sketchfab.com/ie-niels)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sticky-notes-from-poly-by-google-72836a51042c4288bbb13131803f5bcb
Title: Sticky notes from Poly by Google
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function PostItModel(props: any) {
  // @ts-ignore
  const { nodes, materials } = useGLTF('/postit-transformed.glb')
  return (
    <group {...props} dispose={null} >
      <mesh geometry={nodes.Object_4.geometry} material={materials.PaletteMaterial001} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.PaletteMaterial002} />
    </group>
  )
}

useGLTF.preload('/postit-transformed.glb')
