/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf --transform
Files: scene.gltf [8.34KB] > scene-transformed.glb [3.86KB] (54%)
Author: Cxrly97 (https://sketchfab.com/Cxrly97)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sticky-notes-7b7204deac514fbbabb367cd74a6a09a
Title: Sticky Notes
*/

// import React, { useRef } from 'react'
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/scene-transformed.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pPlane4_lambert28_0.geometry}
        material={materials.lambert28}
        position={[394.607, 219.523, -447.742]}
        rotation={[1.384, -0.184, 0.768]}
        scale={19.667}
      />
      <mesh
        geometry={nodes.pPlane5_lambert30_0.geometry}
        material={materials.lambert30}
        position={[391.387, 187.029, -450.13]}
        rotation={[1.384, -0.184, 0.768]}
        scale={19.667}
      />
      <mesh
        geometry={nodes.pPlane3_lambert29_0.geometry}
        material={materials.lambert29}
        position={[373.583, 207.953, -467.769]}
        rotation={[1.384, -0.184, 0.768]}
        scale={19.667}
      />
    </group>
  );
}

useGLTF.preload("/scene-transformed.glb");
